# This file was generated by GoReleaser. DO NOT EDIT.
class Baleia < Formula
  desc "Baleia is a template engine used to manage Docker images templates repositories."
  homepage "https://julienbreux.github.io/baleia/"
  version "0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/JulienBreux/baleia/releases/download/v0.6/baleia_0.6_Darwin_x86_64.tar.gz"
    sha256 "ac37cfeeba5fcec3868e291b1a0e4b6b7f50dfef89377d29cabfc9864ace72b5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/JulienBreux/baleia/releases/download/v0.6/baleia_0.6_Linux_x86_64.tar.gz"
      sha256 "accf5d6e39a777856d42b01ec36c4bae692f3ed7676b0d12e29322a82afcd581"
    end
  end

  def install
    bin.install "baleia"
  end

  test do
    system "baleia version"
  end
end
