# This file was generated by GoReleaser. DO NOT EDIT.
class Baleia < Formula
  desc "Baleia is a template engine used to manage Docker images templates repositories."
  homepage "https://julienbreux.github.io/baleia/"
  version "0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/JulienBreux/baleia/releases/download/v0.4/baleia_0.4_Darwin_x86_64.tar.gz"
    sha256 "02a3a6b5c66ec89221f8eee2edb142733a7da7cd4d8b4386a789f7f7adc7b744"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/JulienBreux/baleia/releases/download/v0.4/baleia_0.4_Linux_x86_64.tar.gz"
      sha256 "3c154d875babf71e74d574ee950dbb91c6a9a4fb99445a117e40d687fb0defb7"
    end
  end

  def install
    bin.install "baleia"
  end

  test do
    system "baleia version"
  end
end
